name: Continuous Integration for dianaflorez

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Pruebas de SAST (mockeado con un echo)
      - name: Pruebas de SAST
        run: echo "Ejecución de pruebas de SAST"

      # Paso 2: Instalar Docker (opcional, por si hay problemas con Docker)
      - name: Instalar Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker
          sudo usermod -aG docker $USER

     

